CREATE SCHEMA PRTS;
USE PRTS;

CREATE TABLE Pothole (
	pothole_id INT PRIMARY KEY AUTO_INCREMENT, 
	size INT NOT NULL,
	address VARCHAR(255) NOT NULL,
	location ENUM(MIDDLE, CURB, TOP, BOTTOM),
	district VARCHAR(255), NOT NULL,
	priority ENUM(LOW, MEDIUM, HIGH)

); 